/* eslint-disable react/no-unescaped-entities */
import { useEffect } from "react";
import Typewriter from "typewriter-effect/dist/core";
import Head from "next/head";

export default function Home() {
  useEffect(() => {
    new Typewriter("#cover-text", {
      strings: [
        "Developer",
        "Teaching Assistant",
        "Petrol-head",
        "Product Manager",
        "Learner",
        "Investor",
      ],
      autoStart: true,
      loop: true,
      deleteSpeed: 50,
    });
  }, []);

  return (
    <div id="container">
      <Head>
        <title>JustinHuang - A Restless Soul 👨🏻‍💻</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="author" content="JustinHuang" />
        <meta name="copyright" content="JustinHuang" />
        <meta itemProp="name" content="JustinHuang" />
        <meta
          itemProp="image"
          content="/_next/static/media/matrix.c18336991b6e7bfc1a5c825957d28863.jpg"
        />
        <meta itemProp="description" content="Hi, I'm Justin" />
        <meta property="og:title" content="JustinHuang - A Restless Soul" />
        <meta property="og:url" content="網址" />
        <meta
          property="og:image"
          content="/_next/static/media/matrix.c18336991b6e7bfc1a5c825957d28863.jpg"
        />
        <meta property="og:description" content="Hi, I'm Justin"></meta>
      </Head>
      <div id="cover">
        <div id="cover-text"></div>
      </div>
      <section id="intro" className="wrapper">
        <div id="intro-image"></div>
        <div id="intro-content">
          <div className="title" data-aos="fade-up">
            <h2>賈斯丁黃</h2>
            <h3>不安分的靈魂</h3>
          </div>
          <div className="content" data-aos="fade-up">
            一個非典型技術宅，鑽研技術也享受打造產品和琢磨細節的過程，被敏捷開發燒到後決定前往軟體領域一探究竟。
            <br />
            目前在電商產業擔任前端工程師，也在程式教育機構兼職助教。
          </div>
          <div className="content" data-aos="fade-up">
            汽車愛好者，對德國工藝特別著迷，尤其是賓士全方位的產品配置和保時捷獨樹一格的德式激情。
            <br />
            喜歡分析市場和規格，曾在台灣唯一整車研發企業擔任產品經理。
          </div>
          <div className="content" data-aos="fade-up">
            指數化投資的實踐者，經歷美股兩週四次熔斷和後續V型反轉的洗禮後，領悟了一套適合自己的投資哲學。
          </div>
        </div>
      </section>
      <section id="developer" className="downtime-wrapper">
        <div className="downtime-title" data-aos="fade-up">
          資訊科技
        </div>
        <div className="content" data-aos="fade-up">
          資訊科技已經大幅改變人類的生活型態，我們每天都需要用到各式各樣的 Web
          或 App，能夠親手打造是一件很酷的事情。
          <br />
          主要專注於前端領域，擅長用 React.js 生態系工具打造網頁應用程式。
          對於技術抱持開放的態度，偶而也會自己玩玩後端及 DevOps 相關技術。
        </div>
      </section>
      <section id="petrolHead" className="downtime-wrapper">
        <div className="downtime-title" data-aos="fade-up">
          汽車
        </div>
        <div className="content" data-aos="fade-up">
          汽車是人類智慧的結晶，力與美的結合，也是個人特色的展現。
          假日爬得起來的話會在清晨去106縣道兜風，幸運的話可以獲得美美的追焦照。
          生在資訊爆炸的時代讓玩車更容易，卻也感嘆內燃機的時代已經進入倒數計時。
        </div>
      </section>
      <section id="ta" className="downtime-wrapper">
        <div className="downtime-title" data-aos="fade-up">
          教育
        </div>
        <div className="content" data-aos="fade-up">
          擔任助教除了批改作業，也時常從學生提出的問題中學習，或是看到自己也可以更進步的地方，教學相長。
        </div>
      </section>
      <section id="sharing" className="downtime-wrapper">
        <div className="downtime-title" data-aos="fade-up">
          分享
        </div>
        <div className="content" data-aos="fade-up">
          在 Medium
          分享自己撰寫的文章，主題包含程式、轉職、面試、技術筆記。(換工作太忙所以有一陣子沒寫了QQ)
        </div>
      </section>
      <section id="movie" className="downtime-wrapper">
        <div className="downtime-title" data-aos="fade-up">
          電影
        </div>
        <div className="content" data-aos="fade-up">
          愛看科幻電影滿足想像力，像是駭客任務、星際大戰、黑暗騎士、全面啟動、普羅米修斯、天能等等;也喜歡昆丁塔倫提諾獨特的暴力美學和敘事手法，像是惡棍特工、決殺令、八惡人、從前有個好萊塢。
        </div>
      </section>
      <section id="sea" className="downtime-wrapper">
        <div className="downtime-title" data-aos="fade-up">
          看海
        </div>
        <div className="content" data-aos="fade-up">
          遠離塵囂靜靜坐在岸邊，看著一望無際的海洋、聽著海浪拍打沙灘的聲音，心靈就療癒了。
        </div>
      </section>
      <section id="contact" className="wrapper">
        <div className="title">Further Information</div>
        <div className="content">
          <div id="linkedIn" className="card" data-aos="zoom-in">
            <a
              target="_tab"
              rel="noopener noreferrer"
              href="https://linkedin.com/in/justinhuang777"
            ></a>
          </div>
          <div id="github" className="card" data-aos="zoom-in">
            <a
              target="_tab"
              rel="noopener noreferrer"
              href="https://github.com/ShihTingJustin"
            ></a>
          </div>
          <div id="medium" className="card" data-aos="zoom-in">
            <a
              target="_tab"
              rel="noopener noreferrer"
              href="https://medium.com/life-after-hello-world"
            ></a>
          </div>
          <div id="instagram" className="card" data-aos="zoom-in">
            <a
              target="_tab"
              rel="noopener noreferrer"
              href="https://www.instagram.com/mb722656355s/"
            ></a>
          </div>
        </div>
      </section>
    </div>
  );
}
